name: Daily_Update_Backend_Dev

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run update script on AWS dev
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.AWS_DEV_HOST }}
          key: ${{ secrets.AWS_DEV_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            set -e
            cd 311-data/server
            docker-compose run api python bin/db_update.py
