on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: ${{secrets.DB_URL}}/ingest?years=2017,2018,2019,2020 &
